name: Update dependencies

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v16
    - name: Update inputs
      # Only update meaningful lock entries.
      run: |
        jq -r '.nodes.root.inputs | map(.) | .[]' flake.lock \
          | grep -vE '^(melpa|gnu-elpa|nixpkgs|root)$' \
          | sed -e 's/^/--update-input /' \
          | xargs nix flake lock
    - name: Check differences
      run: git diff-index --exit-code --name-status HEAD
      id: diff
      continue-on-error: true
    - name: Create a pull request
      uses: peter-evans/create-pull-request@v4.0.1
      if: ${{ steps.diff.outcome == 'failure' }}
      with:
        commit-message: 'Update flake inputs'
        base: master
        title: 'chore(deps): Update dependencies'
        branch: create-pull-request/update
        delete-branch: true
        labels: automation,update
