name: Update dependencies

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - name: Update inputs
      # Only update meaningful lock entries.
      run: |
        jq -r '.nodes.root.inputs | map(.) | .[]' flake.lock \
          | grep -vE '^(melpa|gnu-elpa|epkgs|emacs|emacs-ci|nixpkgs|root)$' \
          | sed -e 's/^/--update-input /' \
          | xargs nix flake lock
    - name: Create a pull request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: 'Update flake inputs'
        base: master
        title: 'chore(deps): Update dependencies'
        branch: create-pull-request/update
        delete-branch: true
        labels: automation,update
