name: Update the lock files for tests

on:
  pull_request:
    paths:
    - flake.lock

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Add missing lock entries
      working-directory: ./tests/good-1
      run: nix flake lock

    - name: Check differences
      run: git diff-index --exit-code --name-status HEAD
      id: diff
      continue-on-error: true
    - name: Create a pull request
      uses: peter-evans/create-pull-request@v4
      if: ${{ steps.diff.outcome == 'failure' }}
      with:
        commit-message: 'Add missing lock entries for tests'
        base: master
        title: 'chore(deps): Add lock entries for tests'
        branch: create-pull-request/update-tests
        delete-branch: true
        labels: automation,update
